language: python
python:
  - '3.6'

# safelist
branches:
  only:
    - dev

before_script:
  - pip install pipenv && pipenv install 

services:
  - postgresql

addons:
  postgresql: "9.6"

env: 
  - DJANGO_SETTINGS_MODULE=testdb.settings.travis

script:
  - pipenv run python manage.py test
